---
- import_playbook: "./playbooks/dotfiles.yml"

- import_playbook: "./playbooks/nodejs.yml"

- import_playbook: "./playbooks/deno.yml"

- import_playbook: "./playbooks/go.yml"

- import_playbook: "./playbooks/rust.yml"

- import_playbook: "./playbooks/docker.yml"

- import_playbook: "./playbooks/kubernetes.yml"

- import_playbook: "./playbooks/minikube.yml"

- import_playbook: "./playbooks/helm.yml"

- import_playbook: "./playbooks/nvim.yml"

- import_playbook: "./playbooks/github.yml"

- import_playbook: "./playbooks/gh.yml"

