---
- name: Install deno
  hosts: localhost
  tags: deno

  tasks:
    - name: Check if deno is installed
      ansible.builtin.shell: command -v deno
      register: deno_exists
      ignore_errors: true

    - name: Update deno
      when: deno_exists is succeeded
      ansible.builtin.shell: deno upgrade

    - name: Install deno
      when: deno_exists is failed
      block:
        - name: Install prerequisities
          ansible.builtin.package:
            name: "{{ item }}"
            state: present
          become: true
          with_items:
            - curl
            - unzip

        - name: Run deno installer script
          ansible.builtin.shell: curl -fsSL https://deno.land/install.sh | sh
          args:
            creates: "{{ ansible_env.HOME }}/.deno"

        - name: Add deno to PATH
          ansible.builtin.blockinfile:
            path: "{{ ansible_env.HOME }}/.zshrc"
            marker: "# deno {mark}"
            marker_begin: ""
            marker_end: "end"
            block: |
              export DENO_INSTALL="/home/maxpushka/.deno"
              export PATH="$DENO_INSTALL/bin:$PATH"
