- name: Authenticate and setup GitHub CLI
  hosts: localhost
  tags: gh

  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - fzf
        - git

    - name: Check if GitHub CLI is authenticated
      shell: gh api user

    - name: Set up Git
      shell: gh auth setup-git

    - name: Install extension if it does not exist
      shell:
        cmd: |
          p={{ item }}
          if [ ! -d {{ ansible_env.HOME }}/.local/share/gh/extensions/${p#*/} ]
          then
            echo "installing {{ item }}..."
            gh extension install "{{ item }}"
          fi
      with_items:
        - "meiji163/gh-notify"
        - "dlvhdr/gh-prs"
        - "kawarimidoll/gh-q"

    - name: Set aliases
      vars:
        gh_aliases:
          listall: "api user/repos --jq '.[].full_name'"
          prv: "pr view -w"
          prc: "pr create"
      command:
        cmd: "gh alias set --clobber {{ item.key }} \"{{ item.value }}\""
      loop: "{{ lookup('dict', gh_aliases) }}"
