- name: Authenticate and setup GitHub CLI
  hosts: localhost
  tags: gh

  vars:
    github_token: "{{ lookup('env','GITHUB_PERSONAL_ACCESS_TOKEN') }}"

  tasks:
    - name: Authenticate
      shell:
        cmd: echo "{{ github_token }}" | gh auth login --with-token && gh auth setup-git

    - name: Install dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - fzf
        - git

    - name: Install extension if it does not exist
      shell:
        cmd: |
          p={{ item }}
          if [ ! -d {{ ansible_env.HOME }}/.local/share/gh/extensions/${p#*/} ]
          then
            echo "installing {{ item }}..."
            gh extension install "{{ item }}"
          fi
      with_items:
        - "meiji163/gh-notify"
        - "dlvhdr/gh-prs"
        - "kawarimidoll/gh-q"

    - name: Set aliases
      command:
        cmd: |
          gh alias set listall "api user/repos --jq '.[].full_name'"
          gh alias set prv "pr view -w"
          gh alias set prc "pr create"

