---
- name: "Install utilities from GitHub"
  hosts: localhost
  tags: github

  vars:
    brew_apps:
      - gh
      - go-task
      - gitui
      - ghq
      - goose
      - git-delta
      - act
      - mike-engel/jwt-cli/jwt-cli
      - solidity # TODO: brew tap ethereum/ethereum
      - neovim
      - golangci-lint

  tasks:
    - name: Install from Homebrew
      ansible.builtin.homebrew:
        name: "{{ item }}"
        state: latest
      with_items: "{{ brew_apps }}"
