---
- name: "Install Homebrew and some apps"
  hosts: localhost
  tags: homebrew

  vars:
    brew_apps:
      - gcc # may be required to build formulae from source
      - gh
      - go-task
      - gitui
      - ghq
      - goose
      - git-delta
      - neovim
      - helix
      - golangci-lint
      - helm
      - deno
      - rust
      - docker-compose
      - kubectl
      - btop
      - pnpm
      - tokei
      - zellij
      - eza
      - ripgrep
      - fd
      - fzf
      - bat
      - starship
      - zoxide
      - grpcurl
      - jdtls
      - gradle
      - zsh-autosuggestions # for Fish-like command completion

  tasks:
    - name: Set Homebrew installation path based on OS
      set_fact:
        homebrew_install_path: "/opt/homebrew/bin/brew"
      when: ansible_os_family == "Darwin"

    - name: Set Homebrew installation path based on OS
      set_fact:
        homebrew_install_path: "/home/linuxbrew/.linuxbrew/bin/brew"
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

    - name: Check if Homebrew is installed
      shell: command -v brew
      register: brew_exists
      ignore_errors: true

    - name: Install Homebrew
      when: brew_exists is failed
      block:
        - name: Run installer script
          shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        - name: Add Homebrew to shell profiles
          shell: |
            echo 'eval "$({{ homebrew_install_path }} shellenv)"' >> {{ ansible_env.HOME }}/{{ item }}
          loop:
            - .zprofile
            - .bash_profile
            - .bashrc

    - name: Install apps from Homebrew
      ansible.builtin.homebrew:
        name: "{{ item }}"
        state: latest
      with_items: "{{ brew_apps }}"
      ignore_errors: true
