---
- name: Setup neovim
  hosts: localhost
  tags: nvim

  vars:
    source_zshrc: . {{ ansible_env.HOME }}/.zshrc

  tasks:
    - name: install packer
      block:
        - name: install git
          ansible.builtin.package:
            name: git
            state: present
          become: "{{ ansible_distribution != 'MacOSX' }}"
        - ansible.builtin.git:
            repo: https://github.com/wbthomason/packer.nvim
            dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
            depth: 1
            update: yes

    - name: install plugin dependencies
      block:
        - name: install python connector package for neovim
          block:
            - name: Install or update pip
              ansible.builtin.package:
                name: "{{ item }}"
                state: present
              become: "{{ ansible_distribution != 'MacOSX' }}"
              ignore_errors: true
              with_items:
                - python-pip
                - python3-pip
            - ansible.builtin.pip:
                name: pynvim

        - name: install packages
          ansible.builtin.package:
            name: "{{ item }}"
            state: present
          become: true
          ignore_errors: true
          with_items:
            - luajit
            - ripgrep
            - fzf
            - gcc   # for tree-sitter
            - clang # for tree-sitter
            - fd
            - fd-find
            - libsqlite3-dev # for neoclip
            - sqlite-devel   # for neoclip

        - name: Install global node packages
          shell: >
            /bin/zsh -c "{{ source_zshrc }} && pnpm -g add {{ item }}"
          loop:
            - neovim typescript
            - tree-sitter-cli
            - eslint_d prettier

