---
- name: Install rust
  tags: rust
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: update repositories
      ansible.builtin.package:
        update_cache: yes
      become_user: root
      changed_when: false

  tasks:
    - name: Check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: true

    - name: Update rust
      when: cargo_exists is succeeded
      command: rustup update

    - name: Install rust
      when: cargo_exists is failed
      block:
        - name: Download installer
          get_url:
            url: https://sh.rustup.rs
            dest: /tmp/sh.rustup.rs
            mode: "0755"
            force: "yes"
        - name: Install rust/cargo
          shell: /tmp/sh.rustup.rs -y

