---
- name: Install ghq
  hosts: localhost
  tags: ghq

  vars:
    github_token: "{{ lookup('env','GITHUB_PERSONAL_ACCESS_TOKEN') }}"
  
  tasks:
    - name: Try to get installed version
      block:
        - shell: echo v$(ghq --version | cut -d ' ' -f 3)
          register: ghq_installed 
          ignore_errors: true
        - name: Print installed version
          ansible.builtin.debug:
            var: ghq_installed

    - name: Get latest release from Github
      block:
        - name: Install or update pip
          ansible.builtin.package:
            name: "{{ item }}"
            state: present
          become: true
          ignore_errors: true
          with_items:
            - python-pip
            - python3-pip
        - name: Install github3 python package
          ansible.builtin.pip:
            name: github3.py
        - community.general.github_release:
            user: x-motemen 
            repo: ghq
            action: latest_release
            token: "{{ github_token }}"
          register: ghq_release
        - name: Print Latest release
          ansible.builtin.debug:
            var: ghq_release
        
    - name: Install latest version
      when: ghq_installed.stdout_lines[0] != ghq_release.tag
      block:
        - name: Download Binary
          ansible.builtin.unarchive:
            src: https://github.com/x-motemen/ghq/releases/download/{{ ghq_release.tag }}/ghq_linux_amd64.zip
            dest: /tmp
            remote_src: true

        - name: Install Binary
          ansible.builtin.copy:
            src: /tmp/ghq_linux_amd64/ghq
            dest: "/usr/local/bin"
            mode: a+x
          become: true